apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: tcprod-grafana
    app.kubernetes.io/name: tcprod-grafana
    app.kubernetes.io/part-of: tcprod-prometheus
    app.kubernetes.io/version: 7.3.7
  name: tcprod-grafana
  namespace: tcprod-pg
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: tcprod-grafana
    app.kubernetes.io/name: tcprod-grafana
    app.kubernetes.io/part-of: tcprod-prometheus
  sessionAffinity: None
  type: NodePort
