apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    persistentvolumeclaims: "30"
    services: "20" 
    pods: "150"

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources-scoped
spec:
  hard:
    requests.memory: 4Gi
    requests.cpu: 3000m
    limits.memory: 10Gi
    limits.cpu: 6000m
  scopes:
  - NotTerminating
