apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: tcprod-grafana
    app.kubernetes.io/name: tcprod-grafana
    app.kubernetes.io/part-of: tcprod-prometheus
    app.kubernetes.io/version: 7.3.7
  name: tcprod-grafana-datasources
  namespace: tcprod-pg  
data:
  datasource.yaml: |-
    {
      "apiVersion": 1,
      "datasources": [
          {
              "access": "proxy",
              "editable": true,
              "name": "Prometheus",
              "orgId": 1,
              "type": "prometheus",
              "url": "http://tcprod-prometheus.tcprod-pg.svc.cluster.local:9090",
              "version": 1
          },
          {
              "access": "proxy",
              "editable": true,
              "name": "Elasticsearch",
              "orgId": 1,
              "type": "elasticsearch",
              "url": "http://tcprod-elastic.tcprod-efk.svc.cluster.local:9200",
              "version": 1,
              "database": "[logstash-*]",
              "jsonData": {
                "interval": "Daily",
                "timefield": "@timestamp",
                "esVersion" : 70,
                "logMessageField": "message",
                "logLevelField": "fields.level"
            }
          }
      ]
    }


 
