namePrefix: 

resources:
  - grafana-token-secret.yaml
  - grafana-datasource-secret.yaml
  - serviceaccount.yaml
  - grafana-dashboard-node-cluster-configmap.yaml
  - grafana-dashboards-configmap.yaml
  - promethues-configmap.yaml
  - grafana-service.yaml
  - grafana-deploy.yaml
  - prometheus-deploy.yaml
  - renderer-service.yaml
  - renderer-deploy.yaml

