apiVersion: v1
kind: Service
metadata:
  name: tcprod-renderer
  namespace: tcprod-pg
  labels:
    app: tcprod-renderer
    app.kubernetes.io/component: tcprod-renderer
    app.kubernetes.io/instance: tcprod-renderer
    name: tcprod-renderer
spec:
  ports:
    - name: tcprod-renderer
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    name: tcprod-renderer
  type: NodePort
