apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  namespace: tcprod-pg
  labels:
    app: tcpord-tcprod-renderer
    app.kubernetes.io/component: tcprod-renderer
    app.kubernetes.io/instance: tcprod-renderer
    name: tcprod-renderer
  name: tcprod-renderer
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  revisionHistoryLimit: 10

  selector:
    matchLabels:
      app.kubernetes.io: tcprod-renderer
  template:
    metadata:
      labels:
        app.kubernetes.io: tcprod-renderer
        name: tcprod-renderer
    spec:
      containers:
        - resources:
            limits:
              cpu: 2000m
              memory: 2000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8081
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1
          terminationMessagePath: /dev/termination-log
          name: tcprod-renderer
          livenessProbe:
            httpGet:
              path: /
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 55
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 2
          env:
            - name: ENABLE_METRICS
              value: "true"
            - name: RENDERING_MODE
              value: "clustered"
            - name: RENDERING_CLUSTERING_MODE
              value: "context"
            - name: RENDERING_CLUSTERING_MAX_CONCURRENNCY
              value: "5"
          ports:
            - containerPort: 8081
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
                  docker.io/grafana/grafana-image-renderer:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
